FROM lukemathwalker/cargo-chef:latest-rust-alpine as chef
WORKDIR /app

FROM chef AS planner
COPY ./Cargo.toml ./Cargo.lock ./
COPY ./src ./src
RUN cargo chef prepare

FROM chef AS builder
COPY --from=planner /app/recipe.json .
RUN cargo chef cook --release
COPY . .
RUN cargo build --release
RUN mv ./target/release/smbackup ./app


# from scratch if you want to go minimal and dont depend on any other libs
FROM alpine AS runtime
WORKDIR /app
COPY --from=builder /app/app /usr/local/bin/
# Mein zeugs
ENV REPLICATION_LOCATIONS=/data
RUN mkdir -p /data

ENTRYPOINT ["/usr/local/bin/app"]